# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    sample = None
    substrates = None
    objective = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuSamples = QtWidgets.QMenu(self.menubar)
        self.menuSamples.setObjectName("menuSamples")
        self.menuSubstrates = QtWidgets.QMenu(self.menubar)
        self.menuSubstrates.setObjectName("menuSubstrates")
        self.menuSiO2_Si = QtWidgets.QMenu(self.menuSubstrates)
        self.menuSiO2_Si.setObjectName("menuSiO2_Si")
        self.menuObjective = QtWidgets.QMenu(self.menubar)
        self.menuObjective.setObjectName("menuObjective")
        MainWindow.setMenuBar(self.menubar)
        self.actionMoS2 = QtWidgets.QAction(MainWindow)
        self.actionMoS2.setObjectName("actionMoS2")
        self.actionMoS2.triggered.connect(self.selectSampleMoS2)
        self.actionWS2 = QtWidgets.QAction(MainWindow)
        self.actionWS2.setObjectName("actionWS2")
        self.actionWSe2 = QtWidgets.QAction(MainWindow)
        self.actionWSe2.setObjectName("actionWSe2")
        self.actionSapphire = QtWidgets.QAction(MainWindow)
        self.actionSapphire.setObjectName("actionSapphire")
        self.actionThickness = QtWidgets.QAction(MainWindow)
        self.actionThickness.setObjectName("actionThickness")
        self.action70nm = QtWidgets.QAction(MainWindow)
        self.action70nm.setObjectName("action70nm")
        self.action270nm = QtWidgets.QAction(MainWindow)
        self.action270nm.setObjectName("action270nm")
        self.action10_X = QtWidgets.QAction(MainWindow)
        self.action10_X.setObjectName("action10_X")
        self.action20 = QtWidgets.QAction(MainWindow)
        self.action20.setObjectName("action20")
        self.action50 = QtWidgets.QAction(MainWindow)
        self.action50.setObjectName("action50")
        self.action100 = QtWidgets.QAction(MainWindow)
        self.action100.setObjectName("action100")
        self.menuSamples.addAction(self.actionMoS2)
        self.menuSamples.addAction(self.actionWS2)
        self.menuSamples.addAction(self.actionWSe2)
        self.menuSiO2_Si.addSeparator()
        self.menuSiO2_Si.addAction(self.actionThickness)
        self.menuSiO2_Si.addSeparator()
        self.menuSiO2_Si.addAction(self.action70nm)
        self.menuSiO2_Si.addAction(self.action270nm)
        self.menuSubstrates.addAction(self.menuSiO2_Si.menuAction())
        self.menuSubstrates.addAction(self.actionSapphire)
        self.menuObjective.addAction(self.action10_X)
        self.menuObjective.addAction(self.action20)
        self.menuObjective.addAction(self.action50)
        self.menuObjective.addAction(self.action100)
        self.menubar.addAction(self.menuSamples.menuAction())
        self.menubar.addAction(self.menuSubstrates.menuAction())
        self.menubar.addAction(self.menuObjective.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuSamples.setTitle(_translate("MainWindow", "Samples"))
        self.menuSubstrates.setTitle(_translate("MainWindow", "Substrates"))
        self.menuSiO2_Si.setTitle(_translate("MainWindow", "SiO2/Si"))
        self.menuObjective.setTitle(_translate("MainWindow", "Objective"))
        self.actionMoS2.setText(_translate("MainWindow", "MoS2"))
        self.actionWS2.setText(_translate("MainWindow", "WS2"))
        self.actionWSe2.setText(_translate("MainWindow", "WSe2"))
        self.actionSapphire.setText(_translate("MainWindow", "Sapphire"))
        self.actionThickness.setText(_translate("MainWindow", "Thickness"))
        self.action70nm.setText(_translate("MainWindow", "70nm"))
        self.action270nm.setText(_translate("MainWindow", "270nm"))
        self.action10_X.setText(_translate("MainWindow", "10 ×"))
        self.action20.setText(_translate("MainWindow", "20 ×"))
        self.action50.setText(_translate("MainWindow", "50 ×"))
        self.action100.setText(_translate("MainWindow", "100 ×"))

    def selectSampleMoS2(self):
        self.sample = 'MoS2'
        self.menuSamples.setTitle('MoS2')

    def selectSampleWS2(self):
        self.sample = 'WS2'
        self.menuSamples.setTitle('WS2')

    def selectSampleWSe2(self):
        self.sample = 'WSe2'
        self.menuSamples.setTitle('WSe2')
